name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pixelateme
            asset_name: PixelateMe-linux-amd64
          - os: windows-latest
            artifact_name: pixelateme.exe
            asset_name: PixelateMe-windows-amd64
          - os: macos-latest
            artifact_name: pixelateme
            asset_name: PixelateMe-macos-amd64

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install patchelf
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: pip install patchelf
    - name: Build Executable
      uses: Nuitka/Nuitka-Action@v0.4
      with:
        script-name: pixelateme/cli.py
        standalone: true
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}